services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres        
      POSTGRES_PASSWORD: 6852 
      POSTGRES_DB: cloud_storage
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    restart: unless-stopped
    ports: 
      - "9001:9001"   
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpassword
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  app:
    build: .
    ports:
      - "9091:9091"
    environment:
      DATABASE_URL: "postgresql://postgres:6852@db:5432/cloud_storage"
      MINIO_ENDPOINT: "minio:9000"
    depends_on:
      - db
      - minio

volumes:
  postgres_data:
  minio_data: